sequenceDiagram

    participant MainVerticle;
    participant WatcherVerticle;
    participant ConverterVerticle;
    participant PairtreeVerticle;
    participant File System;
    participant WaveformVerticle;

    activate MainVerticle

    MainVerticle->>File System: Set up file system watcher

    loop
        File System->>WatcherVerticle: Sends new/updated CSV event
        activate WatcherVerticle

        loop for each item
            alt is audio
                activate ConverterVerticle
                activate PairtreeVerticle
                activate WaveformVerticle

                note over WatcherVerticle,WaveformVerticle: In parallel:<br>(1) converts audio to MP4 and inserts into Pairtree, and<br>(2) generates waveform data and stores on Amazon S3.<br>See diagram below for details.

                deactivate ConverterVerticle
                deactivate PairtreeVerticle
                deactivate WaveformVerticle
            else is video
                WatcherVerticle->>PairtreeVerticle: Sends video file for insertion into Pairtree
                activate PairtreeVerticle

                PairtreeVerticle->>File System: Reads MP4 video file
                PairtreeVerticle-->>WatcherVerticle: Notifies of successful Pairtree insertion
                deactivate PairtreeVerticle
            end
        end

        WatcherVerticle->>File System: Writes modified CSV file
        deactivate WatcherVerticle
    end

    deactivate MainVerticle
